
site_name: Crux Notes
site_url: https://tsolakoua.github.io/cruxnotes/
use_directory_urls: true
site_description: Crux Notes is a trusted climbing resource featuring advice, climbers stories to help you progress on your climbing journey.

theme:
  logo: static/images/logo.png
  name: material
  palette:
    # Light mode
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - announce.dismiss
    - content.code.copy
    - toc.integrate

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - blog

#Page tree
nav:
    - Home: index.md
    - Learnings:
       - Strength: strength.md
       - Hangboard training: hangboard-training.md
    - Blog:
      - blog/index.md
    - Contribution:
      - Contributing: contributing.md
      - Code of conduct: code-of-conduct.md
    - About: about.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tsolakoua/cruxnotes
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tsolakouanna/

  analytics:
    provider: google
    property: G-ZVP56KD0TZ

  consent:
    title: Cookie consent
    description: > # (1)
      We use cookies to recognize your visits, as well
      as to measure the effectiveness of our website and whether users
      find what they're searching for. With your consent, you're helping us to
      make our website better.